#!/bin/bash
# cr_proj_dir
#
# Create directory structure and default configuration file for specified project.
#
# Inputs
#  1. User home directory
#  2. Username
#  3. Project name
#
# Calling Example
#  > ./cr_proj_dir /home/testuser testuser cml


# process command line arguments
DONTCARE=$1  # DEPRECATED

UN=$2           # username
LHD=/home/$UN   # local home directory
RHD=/rhome/$UN  # remote home directory

PN=$3  # project name


# create project directory structure                                                                          
sudo mkdir -p $LHD/Projects
sudo mkdir -p $LHD/Projects/$PN/Figures
sudo mkdir $LHD/Projects/$PN/JobIn
sudo mkdir $LHD/Projects/$PN/JobRunning                                                                        
sudo mkdir $LHD/Projects/$PN/JobOut
sudo mkdir $LHD/Projects/$PN/JobFailed                                                                            
sudo mkdir $LHD/Projects/$PN/Data
sudo mkdir $LHD/Projects/$PN/Data/Jm
sudo mkdir $LHD/Projects/$PN/Archive
sudo mkdir $LHD/Projects/$PN/Suspended                                                                                                  

# change ownership and permissions of project directory structure
sudo chown -R $UN:pcs $LHD/Projects
sudo chmod -R g+rwx $LHD/Projects
                                                                                                                                                  
# set paths to configuration files 
CFN=$PN\_cfg                       # config filename
DCP=/home/pcs/jm/$PN/cfg/$CFN      # default configuration file path
UCLP=$LHD/$CFN                     # user configuration local file path
UCRP=$RHD/$CFN                     # user configuration remote file path

# copy default configuration file to user home directory
sudo cp $DCP $UCLP


# populate configuration file fields with default values                                                      
sudo sed -i "s#<user\_lhome>#$LHD#" $UCLP     # user home directory local path
sudo sed -i "s#<user\_rhome>#$RHD#" $UCLP     # user home directory remote path

sudo chown -R $UN:$UN $UCLP


#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                  
#                                                                                                             
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US                               


