classdef Simulation < handle
    
    properties
        SimParam
        SimState
%         SimParam = struct(...
%             'CodedModObj', [], ...    % Coded modulation object.
%             'ChannelObj', [], ...     % Channel object (Modulation object is a property of channel).
%             'SNRType', 'Es/N0 in dB', ...
%             'SNR', [], ...            % Row vector of SNR points in dB.
%             'MaxTrials', [], ...      % A vector of integers (or a scalar), one for each SNR point. Maximum number of trials to run per point.
%             'FileName', [], ...
%             'SimTime', 300, ...       % Simulation time in Seconds.
%             'CheckPeriod', 10, ...    % Checking time in number of Trials.
%             'MaxBitErrors', [], ...
%             'MaxSymErrors', [], ...
%             'MaxFrameErrors', [], ...
%             'minBER', 1e-8, ...
%             'minSER', 1e-8, ...
%             'minFER', 1e-8 );
% 
%         SimState = struct( ...
%             'Trials', [], ...
%             'SymbolErrors', [], ...
%             'BitErrors', [], ...
%             'FrameErrors', [], ...
%             'SER', [], ...
%             'BER', [], ...
%             'FER', [], ...
%             'NodeID, [], ...
%             'StartTime', [], ...
%             'StopTime', [] );
    end
    
    methods
        function [NumBitError, NumSymbolError] = Trial(obj)
        end
        function SigngleSimulate(obj)
        end
    end
end