#!/bin/bash
# jms
#
# This file stores startup functions for the job managers supported by pcs.
# Add a startup function here to add a job manager.
#
# Functions are named by convention
#  jm_<name>
# where <name> is the job manager name.
# This name is passed to the pcs startup script to specify
#  job manager startup.
#
#  Example
#  Start the job manager having name "cml" in the short queue
#  > pcs short start cml
#
#
#
# All functions accept a single input argument - the queue name
# Queue name takes one value of
# short
# long
# testing 
# The queue name specifies where the job manager must store its task files.
#
#
# Available job managers
#  cml
#  ee561



# CML job manager
jm_cml(){
QCfg=$1

PATH_JM=/home/pcs/jm/cml/src                    # path to CML JM startup script
JM_CFG=/home/pcs/jm/cml/cfg/CmlJobManager_cfg   # path to configuration file

screen -S cml_$Q -m -d matlab -r "cd $PATH_JM; cml_jm_startup('$JM_CFG','$QCfg')"
}



# ee561 job manager
jm_ee561(){
QCfg=$1

PATH_JM=/home/pcs/jm/ee561/src                      # path to EE 561 JM startup script
JM_CFG=/home/pcs/jm/ee561/cfg/ee561JobManager_cfg   # path to configuration file

screen -S ee561_$Q -m -d matlab -r "cd $PATH_JM; ee561_jm_startup('$JM_CFG','$QCfg')"
}
