#!/bin/bash
# spm
#
# Execute multiple CML error-rate speed tests in succession using sp script
#
# Inputs
#  1.   CML Scenario
#  2-N. Record
#
#
#  Calling Examples
#
#  1. Run CML scenario 'SpeedProfile', record 1,2,3
#   > ./spm SpeedProfile 1 2 3
#
#
#  If the requested simulations require a long time to run,
#   it is suggested to run this script in a screen session.
#                                                               
#     Copyright (C) 2013, Terry Ferrett and Matthew C. Valenti   
#     For full copyright information see the bottom of this file.


### Input processing
err_input(){
echo "Improper input arguments."
echo "Usage:"
echo "spm {scenario} {record(s)}"
echo
echo "Example: Execute scenario SpeedProfile records 1-3"
echo "> spm SpeedProfile 1 2 3"
}

# read input arguments
if [ $# -lt 2 ]
then
err_input
exit 1
fi


SCENARIO=$1  # scenario name

# store records in array
k=0
for i in ${@:2}
do
RECORDS[$k]=$i
k=$(($k+1))
done
##################



#### loop over records launching sp for each
for CUR_REC in ${RECORDS[@]}
do

./sp run $SCENARIO $CUR_REC ns

sleep 2
SCR=`screen -ls |grep -i $SCENARIO\_$CUR_REC\_M`

while [ ! -z "$SCR" ]
do
echo "Executing simulations $SCENARIO ${RECORDS[@]}."
echo "Waiting for simulation $SCENARIO $CUR_REC to complete."
SCR=`screen -ls |grep -i $SCENARIO\_$CUR_REC\_M`
sleep 5
done

done
##########################################





#     This library is free software;                                            
#     you can redistribute it and/or modify it under the terms of               
#     the GNU Lesser General Public License as published by the                 
#     Free Software Foundation; either version 2.1 of the License,              
#     or (at your option) any later version.                                    
#                                                                               
#     This library is distributed in the hope that it will be useful,           
#     but WITHOUT ANY WARRANTY; without even the implied warranty of            
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         
#     Lesser General Public License for more details.                           
#                                                                               
#     You should have received a copy of the GNU Lesser General Public          
#     License along with this library; if not, write to the Free Software       
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US


