#!/bin/bash


check_for_screen_session(){
case `screen -ls` in
    *$1*) DONE=0 ;;
    *) DONE=1 ;;
esac

echo $DONE
}




monitor_sims(){  # wait for both MATLAB screen sessions to complete
LOCAL_DONE=0
CLUSTER_DONE=0

while [ $LOCAL_DONE -eq 0 ] && [ $CLUSTER_DONE -eq 0 ]
do

LOCAL_DONE=`check_for_screen_session $1`
CLUSTER_DONE=`check_for_screen_session $2`

sleep 10
done

plot_data
                                     
}


monitor_sims $1 $2