#!/bin/bash
# del_user
#
# script to delete a web-based webcml user
# called from web application

# inputs
# 1. username

# add supporting script directory to path                                                                      
INSTP=/home/pcs/acctm/user
ROOTP=`dirname $INSTP`
SUPPP=$ROOTP/supp
PATH=$PATH:$SUPPP

un=$1                 #username

wup=/home   #web user path

home=$wup/$un

# delete user
sudo deluser --remove-home $un
# NOTE: this implementation will change once the cluster is migrated
#  to Precise and all user accounts are stored in LDAP



#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                   
#                                                                                                              
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US    
