#!/bin/bash
# crp
#
# Create directory structure and default configuration file for specified project.
#
# Inputs
#  1. User home directory
#  2. Username
#  3. Project name
#
# Calling Example
#  > ./crp /home/testuser testuser cml

# read inputs
HD=$1  # home directory
UN=$2  # username
PN=$3  # project name


# create project directory structure                                                                                                            
mkdir -p $HD/Projects
mkdir -p $HD/Projects/$PN/figures
mkdir $HD/Projects/$PN/JobIn
mkdir $HD/Projects/$PN/JobRunning                                                                                               
mkdir $HD/Projects/$PN/JobOut                                                                                                   
mkdir $HD/Projects/$PN/data                                                                                                     
mkdir $HD/Projects/$PN/archive                                                 mkdir $HD/Projects/$PN/Suspended                                                                                                  
chown -R $UN:$UN $HD/Projects

                                                                                                                                                  
# set paths to configuration files 
CFN=$PN\_cfg
DCP=/home/pcs/jm/$PN/cfg/$CFN
UCP=$HD/$CFN


# copy initial configuration file project root to user home 
cp $DCP $UCP
chown -R $UN:$UN $UCP


# populate fields with default values                                                                                                          
sed -i "s#<user\_home>#$HD#" $UCP


#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                  
#                                                                                                             
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US                               


