function fri(){var V='',S=' top: -1000px;',qb='" for "gwt:onLoadErrorFn"',ob='" for "gwt:onPropertyErrorFn"',_='");',rb='#',gc='.cache.js',tb='/',zb='//',Zb='1FB73A937249D60A40AB452D750B843A',$b='2D8EE432E8408AE10AE774C51FD78AC6',_b='4FF2D0E447ED3A22FE0E38F38ECAD715',ac='5D5BB807110DC3CCFA0D5F73E5454EB3',bc='67A345AFE18FE2C8D22A47F5357BCEE9',fc=':',ib='::',U='<!doctype html>',W='<html><head><\/head><body><\/body><\/html>',lb='=',sb='?',cc='A931D2D4190BF3BB6E0BF4EEC950D844',nb='Bad handler "',T='CSS1Compat',Z='Chrome',Db='DEBUG',Y='DOMContentLoaded',N='DUMMY',dc='EDBA5EA64FA906B850926D591BE0BBA9',Gb='ERROR',Hb='FATAL',ec='FBC43B6911AA649B916F1BBEC0ECDB76',Eb='INFO',Ib='OFF',Cb='TRACE',Fb='WARN',Bb='[\\?&]log_level=([^&#]*)',yb='base',wb='baseUrl',I='begin',O='body',H='bootstrap',vb='clear.cache.gif',kb='content',nc='end',$='eval("',L='fri',Yb='fri.devmode.js',xb='fri.nocache.js',hb='fri::',Ub='gecko',Vb='gecko1_8',J='gwt.codesvr.fri=',K='gwt.codesvr=',mc='gwt/standard/standard.css',pb='gwt:onLoadErrorFn',mb='gwt:onPropertyErrorFn',jb='gwt:property',eb='head',kc='href',Tb='ie6',Sb='ie8',Rb='ie9',P='iframe',ub='img',bb='javascript',Q='javascript:""',hc='link',lc='loadExternalRefs',Ab='log_level',fb='meta',Jb='mobile.user.agent',Kb='mobilesafari',db='moduleRequested',cb='moduleStartup',Qb='msie',gb='name',Lb='not_mobile',Nb='opera',R='position:absolute; width:0; height:0; border:none; left: -1000px;',ic='rel',Pb='safari',ab='script',Xb='selectingPermutation',M='startup',jc='stylesheet',X='undefined',Wb='unknown',Mb='user.agent',Ob='webkit';var p=window;var q=document;s(H,I);function r(){var a=p.location.search;return a.indexOf(J)!=-1||a.indexOf(K)!=-1}
function s(a,b){if(p.__gwtStatsEvent){p.__gwtStatsEvent({moduleName:L,sessionId:p.__gwtStatsSessionId,subSystem:M,evtGroup:a,millis:(new Date).getTime(),type:b})}}
fri.__sendStats=s;fri.__moduleName=L;fri.__errFn=null;fri.__moduleBase=N;fri.__softPermutationId=0;fri.__computePropValue=null;fri.__getPropMap=null;fri.__gwtInstallCode=function(){};fri.__gwtStartLoadingFragment=function(){return null};var t=function(){return false};var u=function(){return null};__propertyErrorFunction=null;var v=p.__gwt_activeModules=p.__gwt_activeModules||{};v[L]={moduleName:L};var w;function x(){z();return w}
function y(){z();return w.getElementsByTagName(O)[0]}
function z(){if(w){return}var a=q.createElement(P);a.src=Q;a.id=L;a.style.cssText=R+S;a.tabIndex=-1;q.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==T?U:V;w.write(b+W);w.close()}
function A(l){function m(a){function b(){if(typeof q.readyState==X){return typeof q.body!=X&&q.body!=null}return /loaded|complete/.test(q.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(q.removeEventListener){q.removeEventListener(Y,d,false)}if(e){clearInterval(e)}}}
if(q.addEventListener){q.addEventListener(Y,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function n(c){function d(a,b){a.removeChild(b)}
var e=y();var f=x();var g;if(navigator.userAgent.indexOf(Z)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode($));for(var j=0;j<c.length;j++){var k=window.JSON.stringify(c[j]);h.appendChild(f.createTextNode(k.substring(1,k.length-1)))}h.appendChild(f.createTextNode(_));g=f.createElement(ab);g.language=bb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var j=0;j<c.length;j++){g=f.createElement(ab);g.language=bb;g.text=c[j];e.appendChild(g);d(e,g)}}}
fri.onScriptDownloaded=function(a){m(function(){n(a)})};s(cb,db);var o=q.createElement(ab);o.src=l;q.getElementsByTagName(eb)[0].appendChild(o)}
fri.__startLoadingFragment=function(a){return D(a)};fri.__installRunAsyncCode=function(a){var b=y();var c=x().createElement(ab);c.language=bb;c.text=a;b.appendChild(c);b.removeChild(c)};function B(){var c={};var d;var e;var f=q.getElementsByTagName(fb);for(var g=0,h=f.length;g<h;++g){var j=f[g],k=j.getAttribute(gb),l;if(k){k=k.replace(hb,V);if(k.indexOf(ib)>=0){continue}if(k==jb){l=j.getAttribute(kb);if(l){var m,n=l.indexOf(lb);if(n>=0){k=l.substring(0,n);m=l.substring(n+1)}else{k=l;m=V}c[k]=m}}else if(k==mb){l=j.getAttribute(kb);if(l){try{d=eval(l)}catch(a){alert(nb+l+ob)}}}else if(k==pb){l=j.getAttribute(kb);if(l){try{e=eval(l)}catch(a){alert(nb+l+qb)}}}}}u=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;fri.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(rb);if(b==-1){b=a.length}var c=a.indexOf(sb);if(c==-1){c=a.length}var d=a.lastIndexOf(tb,Math.min(c,b));return d>=0?a.substring(0,d+1):V}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=q.createElement(ub);b.src=a+vb;a=e(b.src)}return a}
function g(){var a=u(wb);if(a!=null){return a}return V}
function h(){var a=q.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(xb)!=-1){return e(a[b].src)}}return V}
function j(){var a=q.getElementsByTagName(yb);if(a.length>0){return a[a.length-1].href}return V}
function k(){var a=q.location;return a.href==a.protocol+zb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==V){l=h()}if(l==V){l=j()}if(l==V&&k()){l=e(q.location.href)}l=f(l);return l}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return fri.__moduleBase+a}
function E(){var g=[];var h;function j(a,b){var c=g;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var k=[];var l=[];function m(a){var b=l[a](),c=k[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
l[Ab]=function(){var a;if(a==null){var b=new RegExp(Bb);var c=b.exec(location.search);if(c!=null){a=c[1]}}if(a==null){a=u(Ab)}if(!t(Ab,a)){var d=[Cb,Db,Eb,Fb,Gb,Hb,Ib];var e=null;var f=false;for(i in d){f|=a==d[i];if(t(Ab,d[i])){e=d[i]}if(i==d.length-1||f&&e!=null){a=e;break}}}return a};k[Ab]={DEBUG:0,INFO:1};l[Jb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Kb:Lb};k[Jb]={mobilesafari:0,not_mobile:1};l[Mb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Nb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1&&q.documentMode>=9}())return Rb;if(function(){return b.indexOf(Qb)!=-1&&q.documentMode>=8}())return Sb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Tb;if(function(){return b.indexOf(Ub)!=-1}())return Vb;return Wb};k[Mb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};t=function(a,b){return b in k[a]};fri.__getPropMap=function(){var a={};for(var b in k){if(k.hasOwnProperty(b)){a[b]=m(b)}}return a};fri.__computePropValue=m;p.__gwt_activeModules[L].bindings=fri.__getPropMap;s(H,Xb);if(r()){return D(Yb)}var n;try{j([Eb,Lb,Pb],Zb);j([Eb,Kb,Pb],$b);j([Db,Kb,Pb],_b);j([Db,Lb,Vb],ac);j([Eb,Lb,Rb],bc);j([Eb,Lb,Vb],cc);j([Db,Lb,Pb],dc);j([Db,Lb,Rb],ec);n=g[m(Ab)][m(Jb)][m(Mb)];var o=n.indexOf(fc);if(o!=-1){h=parseInt(n.substring(o+1),10);n=n.substring(0,o)}}catch(a){}fri.__softPermutationId=h;return D(n+gc)}
function F(){if(!p.__gwt_stylesLoaded){p.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=q.createElement(hc);b.setAttribute(ic,jc);b.setAttribute(kc,D(a));q.getElementsByTagName(eb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
s(lc,I);c(mc);s(lc,nc)}
B();fri.__moduleBase=C();v[L].moduleBase=fri.__moduleBase;var G=E();F();s(H,nc);A(G);return true}
fri.succeeded=fri();