#!/bin/bash
# dproj
#
# Download project code for user
#
# Inputs
#  1. User home directory
#  2. Username
#  3. Project name


# read inputs
HD=$1    # home directory
UN=$2    # username
PN=$3    # project directory

# download project code, anonymous access
svn co http://iscml.googlecode.com/svn/trunk/pcs/projects/$PN $HD/$PN
chown -R $UN:$UN $HD/$PN


#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                  
#                                                                                                             
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US                               