#!/bin/bash
# cr_user.sh
#
# script to create a web-based webcml user
# called from web application

# inputs
# 1. username

# add supporting script directory to path                                                                      
INSTP=`pwd`
ROOTP=`dirname $INSTP`
SUPPP=$ROOTP/supp
PATH=$PATH:$SUPPP

un=$1                 #username

wup=/home   #web user path

home=$wup/$un

# create user home directory
sudo adduser --gecos "" --disabled-password $un

cr_task_dir $home $un


#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                   
#                                                                                                              
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US    
