#!/bin/bash
# cr_task_dir
#
# Create task directory structure and default configuration files
#  for specified user.
#
# Inputs
#  1. User home directory.
#  2. Username
#
# Calling example
#  > ./cr_task_dir /home/testuser testuser


# process command line arguments
HD=$1
UN=$2


# create task directory structure                                                                                                               
sudo mkdir $HD/tasks
sudo mkdir $HD/tasks/siq
sudo mkdir $HD/tasks/liq
sudo mkdir $HD/tasks/rq
sudo mkdir $HD/tasks/oq
sudo chown -R $UN:$UN $HD/tasks


# create configuration file for short queue                                                                                                    
sudo sh -c "echo [paths] >> $HD/ctc_cfg"
sudo sh -c "echo input = $HD/tasks/siq >> $HD/ctc_cfg"
sudo sh -c "echo active = $HD/tasks/rq >> $HD/ctc_cfg"
sudo sh -c "echo output = $HD/tasks/oq >> $HD/ctc_cfg"
sudo chown -R $UN:$UN $HD/ctc_cfg


# create configuration file for long queue
sudo sh -c "echo [paths] >> $HD/ctc_cfg_l"
sudo sh -c "echo input = $HD/tasks/liq >> $HD/ctc_cfg_l"
sudo sh -c "echo active = $HD/tasks/rq >> $HD/ctc_cfg_l"
sudo sh -c "echo output = $HD/tasks/oq >> $HD/ctc_cfg_l"
sudo chown -R $UN:$UN $HD/ctc_cfg_l


#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                  
#                                                                                                             
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US