#!/bin/bash
# inst_proj
#
# Install PCS project for cluster/web user.
#
# Inputs
#  1. User home directory
#  2. Username
#  3. Project name
#
# Calling example - install CML for testuser
# > ./install_proj /home/testuser testuser cml
#
#     Copyright (C) 2012, Terry Ferrett and Matthew C. Valenti
#     For full copyright information see the bottom of this file.

# add supporting script directory to path
INSTP=`pwd`
ROOTP=`dirname $INSTP`
SUPPP=$ROOTP/supp
PATH=$PATH:$SUPPP


# read script inputs
HD=$1   # home directory
UN=$2   # username
PN=$3   # project name


# confirm that home directory exists
if [ ! -d $HD ]
then
echo "Directory $HD does not exist."
exit
fi


# create task directory structure and config file
crt $HD $UN

# create project directory structure and config file
crp $HD $UN $PN

# download cml
dcml $HD $UN $PN




#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.
#
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US    