#!/bin/bash
# cr_proj_dir
#
# Create directory structure and default configuration file for specified project.
#
# Inputs
#  1. User home directory
#  2. Username
#  3. Project name
#
# Calling Example
#  > ./create_proj_dir /home/testuser testuser cml


# process command line arguments
HD=$1  # home directory
UN=$2  # username
PN=$3  # project name


# create project directory structure                                                                          
sudo rm -rf $HD/Projects
sudo mkdir -p $HD/Projects
sudo mkdir -p $HD/Projects/$PN/Figures
sudo mkdir $HD/Projects/$PN/JobIn
sudo mkdir $HD/Projects/$PN/JobRunning                                                                        
sudo mkdir $HD/Projects/$PN/JobOut                                                                            
sudo mkdir $HD/Projects/$PN/Data
sudo mkdir $HD/Projects/$PN/Data/Jm
sudo mkdir $HD/Projects/$PN/Archive
sudo mkdir $HD/Projects/$PN/Suspended                                                                                                  

# change ownership and permissions of project directory structure
sudo chown -R $UN:pcs $HD/Projects
sudo chmod -R g+rwx $HD/Projects
                                                                                                                                                  
# set paths to configuration files 
CFN=$PN\_cfg                       # config filename
DCP=/home/pcs/jm/$PN/cfg/$CFN      # default configuration file path
UCP=$HD/$CFN                       # user configuration file path


# copy default configuration file to user home directory
sudo cp $DCP $UCP


# populate configuration file fields with default values                                                      
sudo sed -i "s#<user\_home>#$HD#" $UCP
sudo chown -R $UN:$UN $UCP


#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.                                                                  
#                                                                                                             
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US                               


