#!/bin/bash
# send_project_email
#
# Send an e-mail from the cluster head node using
#  statler-wcrl@mail.wvu.edu as the return address
#
# Called by web interface to send project-specific e-mails.
#
# Inputs
#  1. Recipient address
#  2. Message subject
#  3. Message body
#
# Calling example - send test message to Terry's gmail account
#
# > send_project_email terry.ferrett@gmail.com statler-wcrl-test-subject
#                      statler-wcrl-test-body
#
# 
#     Copyright (C) 2012, Terry Ferrett and Matthew C. Valenti
#     For full copyright information see the bottom of this file.

sendemail -s mail.cemr.wvu.edu\
          -f statler-wcrl@mail.csee.wvu.edu \
          -t $1 \
          -u $2 \
          -m $3

#     This library is free software;                                                                          
#     you can redistribute it and/or modify it under the terms of                                             
#     the GNU Lesser General Public License as published by the                                               
#     Free Software Foundation; either version 2.1 of the License,                                            
#     or (at your option) any later version.
#
#     This library is distributed in the hope that it will be useful,                                         
#     but WITHOUT ANY WARRANTY; without even the implied warranty of                                          
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU                                       
#     Lesser General Public License for more details.                                                         
#                                                                                                             
#     You should have received a copy of the GNU Lesser General Public                                        
#     License along with this library; if not, write to the Free Software                                     
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  US    